-- Definição dos relacionamentos
ALTER TABLE FAQ ADD CONSTRAINT fk_faq_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NOTICIAS ADD CONSTRAINT fk_noticias_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMPARTILHAMENTO ADD CONSTRAINT fk_compartilhamento_noticia FOREIGN KEY (not_id) REFERENCES NOTICIAS(not_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SUPORTE ADD CONSTRAINT fk_suporte_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SUPORTE ADD CONSTRAINT fk_suporte_assunto FOREIGN KEY (asst_id) REFERENCES ASSUNTOS(asst_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PERSONAGENS ADD CONSTRAINT fk_personagens_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ARSENAL ADD CONSTRAINT fk_arsenal_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MAPAS ADD CONSTRAINT fk_mapas_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
