SELECT usu_id, usu_nome, usu_email, usu_senha, usu_data_cadastro, usu_tipo, usu_ativo FROM USUARIOS;
SELECT faq_id, usu_id, faq_pergunta, faq_resposta FROM FAQ;
SELECT not_id, usu_id, not_titulo, not_conteudo, not_imagem, not_data_publicacao FROM NOTICIAS;
SELECT comp_id, not_id, comp_plataforma, comp_data FROM COMPARTILHAMENTO;
SELECT cat_id, cat_nome FROM CATEGORIA;
SELECT asst_id, asst_nome FROM ASSUNTOS;
SELECT sup_id, usu_id, asst_id, sup_mensagem, sup_status, sup_data_criacao, sup_email, sup_nome FROM SUPORTE;
SELECT pers_id, usu_id, pers_tipo, pers_nome, pers_src, pers_alt, pers_descricao, pers_frase, pers_data_criacao FROM PERSONAGENS;
SELECT ars_id, usu_id, ars_tipo, ars_nome, ars_src, ars_alt, ars_dano, ars_raridade, ars_municao, ars_alcance, ars_taxa_disparo, ars_taxa_acerto, ars_data_criacao FROM ARSENAL;
SELECT mapa_id, usu_id, mapa_src, mapa_alt, mapa_nome, mapa_descricao, mapa_data_criacao FROM MAPAS;
